=== hexian000/kcptun-libev/src/conf_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "connect": { "type": "string" },
        "http_listen": { "type": "string" },
        "kcp_bind": { "type": "string" },
        "kcp_connect": { "type": "string" },
        "keepalive": { "type": "integer", "minimum": 0, "maximum": 600, "default": 25 },
        "kcp": {
            "type": "object",
            "properties": {
                "flush":    { "type": "integer", "minimum": 0,   "maximum": 2,     "default": 1   },
                "interval": { "type": "integer", "minimum": 10,  "maximum": 500,   "default": 100 },
                "mtu":      { "type": "integer", "minimum": 300, "maximum": 1500,  "default": 1400 },
                "nc":       { "type": "integer", "minimum": 0,   "maximum": 1,     "default": 1   },
                "nodelay":  { "type": "integer", "minimum": 0,   "maximum": 2,     "default": 1   },
                "rcvwnd":   { "type": "integer", "minimum": 16,  "maximum": 65536, "default": 256 },
                "resend":   { "type": "integer", "minimum": 0,   "maximum": 100,   "default": 0   },
                "sndwnd":   { "type": "integer", "minimum": 16,  "maximum": 65536, "default": 256 }
            }
        },
        "linger": { "type": "integer", "minimum": 5, "maximum": 600, "default": 30 },
        "listen": { "type": "string" },
        "log": { "type": "string" },
        "loglevel": { "type": "integer", "minimum": 0, "maximum": 8, "default": 4 },
        "method": { "type": "string" },
        "netdev": { "type": "string" },
        "obfs": { "type": "string" },
        "password": { "type": "string" },
        "psk": { "type": "string" },
        "rendezvous_server": { "type": "string" },
        "service_id": { "type": "string" },
        "tcp": {
            "type": "object",
            "properties": {
                "keepalive":  { "type": "boolean", "default": false },
                "nodelay":    { "type": "boolean", "default": true  },
                "rcvbuf":     { "type": "integer", "minimum": 0, "maximum": 33554432 },
                "reuseport":  { "type": "boolean", "default": false },
                "sndbuf":     { "type": "integer", "minimum": 0, "maximum": 33554432 }
            }
        },
        "time_wait": { "type": "integer", "minimum": 5,  "maximum": 3600,  "default": 120 },
        "timeout":   { "type": "integer", "minimum": 60, "maximum": 86400, "default": 600 },
        "udp": {
            "type": "object",
            "properties": {
                "rcvbuf":    { "type": "integer", "minimum": 0, "maximum": 33554432 },
                "reuseport": { "type": "boolean", "default": false },
                "sndbuf":    { "type": "integer", "minimum": 0, "maximum": 33554432 }
            }
        },
        "user": { "type": "string" }
    }
}

=== hexian000/kcptun-libev/client.json
{
    "listen": ":5202",
    "kcp_connect": "127.0.0.1:5555",
    "kcp": {
        "mtu": 1492,
        "sndwnd": 256,
        "rcvwnd": 256,
        "nodelay": 1,
        "interval": 100,
        "resend": 0,
        "nc": 1
    },
    "udp": {
        "sndbuf": 1048576,
        "rcvbuf": 1048576
    },
    "method": "xchacha20poly1305_ietf",
    "password": "k",
    "loglevel": 6
}
